- hosts: localhost
  vars_prompt:
       - name: "access_key"
         prompt: "Enter the access key"
         private: no
       - name: "secret_key"
         prompt: "Enter the secret key"
         private: no
       - name: "key_name"
         prompt: "Enter the keyname"
         private: no
       - name: "ec2_region"
         prompt: "Enter the ec2 region"
         private: no
       - name: "instance_type"
         prompt: "Enter the instance type"
         private: no
      - name: "image_id"
         prompt: "Enter the image id"
         private: no
      - name: "group_id"
         prompt: "Enter the security group id"
         private: no
      - name: "sshpath"
         prompt: "Enter the path where key-pair lies on local. Ex:/home/.ssh/nagios.pem"
         private: no

  roles:
       - role: create_instances

  tasks:
       - name: Get IPs
         command: python IP.py {{ec2_region}}
       - name: Wait for EC2 instance
         wait_for: timeout=200
       - name: Checking for ansible connectivity
         command: ansible -m ping all

###############

- hosts: nagios_client
  roles:
       - role: nagios_client_setup

################

- hosts: nagios_core
  roles:
       - role: nagios_core_setup

###############
