- hosts: localhost

  vars_files:
     - vars/main.yml
 
  vars_prompt:
       - name: "access_key"
         prompt: "Enter the access key"
         private: no
       - name: "secret_key"
         prompt: "Enter the secret key"
         private: no
 
  roles:
       - role: 'roles/create_instances'

  tasks:
       - name: Get IPs
         command: python ip_grep.py {{ec2_region}}
       - name: Wait for EC2 instance
         wait_for: timeout=200
       - name: Checking for ansible connectivity
         command: ansible -m ping all

- hosts: nagios_client
  roles:
       - role: 'roles/nagios_client_setup'


- hosts: nagios_core
  roles:
       - role: 'roles/nagios_core_setup'
