- name: Install basic packages.
      yum:
        name: "{{ item }}"
        state: present
      with_items:
             - wget
             - python3
             - net-tools
             - gcc
      ignore_errors: yes

- name: wget epel-release repository
      get_url:
         url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         dest: /
         mode: 0640

- name: Install epel-release repository
      yum:
        name: /epel-release-latest-7.noarch.rpm
        state: present

- name: Install Nagios-Core packages.
      yum:
        name: "{{ item }}"
        state: present
      with_items:
             - nagios     
             - nagios-plugins-all
             - nagios-plugins-nrpe
             - nrpe
             - httpd
             - php

- name: Enable services httpd and nagios for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - httpd
    - nagios
  become: yes

- name: Create 2GB Swap Space
  command: dd if=/dev/zero of=/swap bs=1024 count=2097152
  command: mkswap /swap && chown root. /swap && chmod 0600 /swap && swapon /swap
  command: echo /swap swap swap defaults 0 0 >> /etc/fstab
  command: echo vm.swappiness = 0 >> /etc/sysctl.conf && sysctl -p
  become: yes

- name: Copy nagios.cfg file
      copy:
        dest: /etc/nagios/nagios.cfg
        src: nagios.cfg
        remote_src: no

- name: Make servers directory
      file:
         path: /etc/nagios/servers
         state: directory 

- name: Copy nagios-client.cfg file
      copy:
        dest: /etc/nagios/servers/nagios-client.cfg
        src: nagios-client.cfg
        remote_src: no 

 - name: Configure server to monitor clients
      template: src=nagios-clients.j2 
        dest: /etc/nagios/servers/clients.conf 
        owner: nagios 
        group: nagios 
        mode: 755

    - name: Restart nagios on server to use new configuration
      service: 
        name: nagios 
        state: restarted
