- name: Install basic packages.
      yum:
        name: "{{ item }}"
        state: present
      with_items:
             - wget
             - python3
             - net-tools
             - gcc
      ignore_errors: yes

- name: wget epel-release repository
      get_url:
         url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         dest: /
         mode: 0640

- name: Install epel-release repository
      yum:
        name: /epel-release-latest-7.noarch.rpm
        state: present

- name: Install Nagios-Client packages.
      yum:
        name: "{{ item }}"
        state: present
      with_items:
             - nagios     
             - nagios-plugins-all
             - nagios-plugins-nrpe
             - nrpe

- name: Enable services httpd and nagios for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nrpe
  become: yes

- name: Configure nagios server IP in nrpe configuration file
      lineinfile: 
        dest: /etc/nagios/nrpe.cfg
        regexp: allowed_hosts=
        line: allowed_hosts=127.0.0.1,{{nagios_client}}

- name: Restart services nrpe and nagios for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nrpe
    - nagios
  become: yes
