- name: wget epel-release repository
  get_url:
     url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     dest: /home/ec2-user/
     mode: 0640

- name: Install epel-release repository
  yum:
    name: /home/ec2-user/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Nagios-Client packages.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - nagios     
      - nagios-plugins-all
      - nagios-plugins-nrpe
      - nrpe

- name: Enable services nrpe for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nrpe
  become: yes

- name: lalalla
  lineinfile: 
    path: /etc/nagios/nrpe.cfg
    regexp: 'allowed_hosts='
    line: allowed_hosts={{ nagios_client_ip }}

- name: Restart services nrpe and nagios for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nrpe
    - nagios
  become: yes
